export default {
  login: "Shahab626",
  id: 64855121,
  node_id: "MDQ6VXNlcjY0ODU1MTIx",
  avatar_url: "https://avatars.githubusercontent.com/u/64855121?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Shahab626",
  html_url: "https://github.com/Shahab626",
  followers_url: "https://api.github.com/users/Shahab626/followers",
  following_url:
    "https://api.github.com/users/Shahab626/following{/other_user}",
  gists_url: "https://api.github.com/users/Shahab626/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Shahab626/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Shahab626/subscriptions",
  organizations_url: "https://api.github.com/users/Shahab626/orgs",
  repos_url: "https://api.github.com/users/Shahab626/repos",
  events_url: "https://api.github.com/users/Shahab626/events{/privacy}",
  received_events_url: "https://api.github.com/users/Shahab626/received_events",
  type: "User",
  site_admin: false,
  name: null,
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 9,
  public_gists: 0,
  followers: 1,
  following: 0,
  created_at: "2020-05-05T15:44:40Z",
  updated_at: "2022-07-22T19:44:02Z",
};
